<div class="alert alert-block alert-success">
    <h1 align="center">Machine Learning in Python</h1>
    <h3 align="center">Session 01: Numpy</h3>
    <h4 align="center"><a href="http://www.iran-machinelearning.ir">Soheil Tehranipour</a></h5>
</div>

# Installing NumPy

To install NumPy, we strongly recommend using a scientific Python distribution. If you’re looking for the full instructions for installing NumPy on your operating system, you can find all of the details here.

If you already have Python, you can install NumPy with:

In [ ]:
!conda install numpy

or

In [ ]:
!pip install numpy

# Numpy
NumPy is a Python package which stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object, provide tools for integrating C, C++ etc. 

It is also useful in linear algebra, random number capability etc. NumPy array can also be used as an efficient multi-dimensional container for generic data. Now, let me tell you what exactly is a python numpy array.

<img src = "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/330px-NumPy_logo_2020.svg.png">

## NumPy Array
Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize numpy arrays from nested Python lists and access it elements. In order to perform these numpy operations, the next question which will come in your mind is:

<img src = "https://i.imgur.com/1t7STdM.gif">


# How to import NumPy

Any time you want to use a package or library in your code, you first need to make it accessible.

In order to start using NumPy and all of the functions available in NumPy, you’ll need to import it. This can be easily done with this import statement:

In [113]:
import numpy as np

In [114]:
np.__version__

'1.26.4'

In [115]:
print(np.__version__)

1.26.4



## What’s the difference between a Python list and a NumPy array?

NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogeneous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogeneous.

## Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.


## Creating arrays in numpy

<img src = "https://numpy.org/devdocs/_images/np_create_matrix.png">


In [116]:
a = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<img src = "http://scipy-lectures.org/_images/numpy_indexing.png" style="width: 50%">

In [117]:
print(np.where(a > 5, a, 0))

[[0 0 0]
 [0 0 6]
 [7 8 9]]


In [118]:
print(type(a))

<class 'numpy.ndarray'>


<img src = "https://numpy.org/devdocs/_images/np_indexing.png" style="width: 100%">

In [119]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [120]:
a[0]

array([1, 2, 3])

In [121]:
a[1,2]

6

## Shape and Reshape in numpy

In [122]:
print(a.shape)

(3, 3)


In [123]:
type(a.shape)

tuple

In [124]:
print(a.shape[0])

3


In [125]:
b = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array (or matrix)

In [126]:
b.shape

(2, 3)

In [127]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
print(np.reshape(b, (3, 2)))

[[1 2]
 [3 4]
 [5 6]]


<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="50%"/>



## Reshaping and flattening multidimensional arrays

In [129]:
print(np.reshape(b, (1, -1)))  # -1 means the number of columns will be determined automatically

[[1 2 3 4 5 6]]


In [130]:
print(np.reshape(b, (-1, 1)))   # -1 means the number of rows will be determined automatically

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


There are two popular ways to flatten an array: .flatten() and .ravel(). The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.

## Arrays in numpy

In [131]:
print(a.ndim)

2


In [132]:
print(a.dtype)

int32


In [133]:
c = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)

In [134]:
print(c.dtype)

float64


In [135]:
c

array([[1., 2., 3.],
       [4., 5., 6.]])

In [136]:
print(a.size)  # number of elements

9


In [137]:
a.itemsize

4

In [138]:
print(c.itemsize)  # size of each element (in bytes)

8


## arange in numpy

In [139]:
d1 = np.arange(1, 20, step=4)
print(d1)

[ 1  5  9 13 17]


In [140]:
np.arange

<function numpy.arange>

## linspace in numpy

In [141]:
d2 = np.linspace(1, 2, num=5)
print(d2)

[1.   1.25 1.5  1.75 2.  ]


In [142]:
d3 = np.linspace(1, 2, num=11)
print(d3)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2. ]


### Creating specific arrays
- `np.ones`
- `np.zeros`
- `np.full`
- `np.eye`

<img src="https://numpy.org/devdocs/_images/np_array_dataones.png" /> 

In [143]:
print(np.ones(shape=(3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [144]:
print(np.zeros(shape=(2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [145]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [146]:
print(np.zeros(shape=(2, 3), dtype=np.int32))

[[0 0 0]
 [0 0 0]]


In [147]:
print(5. * np.ones(shape=(3, 2)))

[[5. 5.]
 [5. 5.]
 [5. 5.]]


In [150]:
print(np.full((3, 2) , 5))

[[5 5]
 [5 5]
 [5 5]]


In [152]:
print(np.eye(4,dtype=np.int32))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [93]:
print(np.fliplr(np.eye(4)))

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [94]:
print(np.random.rand(3, 2))

[[0.64130239 0.04270581]
 [0.60419354 0.00254586]
 [0.95007042 0.09845867]]


## Operations on numpy arrays

<img src="https://numpy.org/devdocs/_images/np_sub_mult_divide.png" /> 


In [95]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print(x)
print()
print(y)

[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]


In [96]:
# Elementwise sum; both produce the array
print(x + y)
print()
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [97]:
# Elementwise difference; both produce the array
print(x - y)
print()
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [98]:
# Elementwise product; both produce the array
print(x * y)
print()
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [99]:
# Elementwise division; both produce the array
print(x / y)
print()
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [100]:
# Elementwise square root; produces the array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


# Adding, removing, and sorting elements

In [101]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [102]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [103]:
a = np.array([10, 20, 30, 40])
b = np.array([50, 60, 70, 80])

In [104]:
np.concatenate((a, b))

array([10, 20, 30, 40, 50, 60, 70, 80])

# More useful array operations

<img src="https://numpy.org/devdocs/_images/np_aggregation.png" /> 

In [105]:
a

array([10, 20, 30, 40])

In [106]:
type(a)

numpy.ndarray

In [107]:
a.sum()

100

In [108]:
a.min()

10

In [109]:
a.max()

40

<img src="https://numpy.org/devdocs/_images/np_matrix_aggregation_row.png" /> 


# Flatten() vs. Ravel()

In [157]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [158]:
b.flatten()

array([1, 2, 3, 4, 5, 6])

In [159]:
b.ravel()

array([1, 2, 3, 4, 5, 6])